// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID        int32
	CreatedAt sql.NullTime
	UpdatedAt time.Time
	Name      string
}
